name: Auto-Cancel
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    types:
      - opened
      - closed
      - reopened
      - synchronize
      - ready_for_review

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Get all workflow ids and set to env variable
        run: echo "WORKFLOW_IDS_TO_CANCEL=$(curl https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows -s | jq -r '.workflows | map(.id|tostring) | join(",")')" >> $GITHUB_ENV

      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          workflow_id: ${{ env.WORKFLOW_IDS_TO_CANCEL }}
          access_token: ${{ github.token }}
